name: Bug Report
description: File a bug report
labels: ["bug"]
assignees:
  - tjboldt
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also, what did you expect to happen?
      placeholder: Describe the problem.
    validations:
      required: true
  - type: dropdown
    id: hardware-version
    attributes:
      label: Hardware Version
      description: What version of the hardware are you running?
      options:
        - Fifth Prototype (Purchased from Terence)
        - Fifth Prototype (Self-assembled)
        - Fifth Prototype (Purchased from third party)
        - Fourth Prototype (Purchased from Terence)
        - Fourth Prototype (Self-assembled)
        - Fourth Prototype (Purchased from third party)
    validations:
      required: true
  - type: dropdown
    id: firmware-version
    attributes:
      label: Firmware Version
      description: What version of the firmware are you running? (shown on boot screen)
      options:
        - 000F
        - Older (not shown on boot, pre-2022-Feb-07)
    validations:
      required: true
  - type: dropdown
    id: driver-version
    attributes:
      label: Driver Version
      description: What version of the driver are you running? Check with `RPI a2version`
      options:
        - 0023 (replaced periph.io with rpio)
        - 0022 (added version info)
        - Older (error calling RPI a2version, pre-2022-Feb-07)
    validations:
      required: true
  - type: dropdown
    id: problem-area
    attributes:
      label: Where are you seeing this problem?
      options:
        - Boot
        - ProDOS access
        - SHELL command
        - RPI Command
        - Other
    validations:
      required: true
  - type: dropdown
    id: computer
    attributes:
      label: What computer is this running on?
      options:
        - Apple II
        - Apple II+
        - Apple //e (unenhanced)
        - Apple //e (enhanced / platinum)
        - Apple IIgs
        - Clone II+
        - Other
    validations:
      required: true      
