name: Assembler

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build firmware
      run: |
        export PATH=$PATH:$(pwd)/.cicd
        cd Apple2
        ./assemble.sh

    - name: Compare binaries
      run: |
        export PATH=$PATH:$(pwd)/.cicd 
        cd Apple2
        ./compare.sh